### ISSUE TITLE
Build Failed with GDK-Pixbuf2 2.36.8 on Arch Linux

### ISSUE THREAD

**Issue by NeoChen1024** [SawfishWM/sawfish#27] opened 2017-08-10 10:52 UTC
After I updated my Arch Linux, and restarted it.
I can't start Sawfish with new GDK-Pixbuf, and I can't rebuild Sawfish, Because some symbol is not defined.

Package Version:
extra/gdk-pixbuf 2.36.8-1
aur/librep 0.92.6-1
aur/rep-gtk 0.90.8.3-1
aur/sawfish 1.12.0-1

**Comment by RobertZenz** [comment] 2017-08-10 11:22
The exact output you get would be helpful.

**Comment by NeoChen1024** [comment] 2017-08-11 12:07
Log is here [Make Log](https://thunix.org/~neo_chen/TEMP/makelog)

**Comment by Nanolx** [comment] 2017-08-11 20:42
Is gdk-pixbuf-xlib properly installed? I can't reproduce that behaviour with gdk 2.36.5 on Debian, also none of the functions your make complains about are marked as deprecated.

**Comment by NeoChen1024** [comment] 2017-08-12 10:48
I am building it on **Arch Linux** with GDK-Pixbuf **3.26.8**.
I tried downgrade gdk-pixbuf to 3.26.7, and it works, but I don't want a walkthrough.

**Comment by Nanolx** [comment] 2017-08-22 20:42
having a look at

* https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/gdk-pixbuf2

the issue was fixed with Arch's 2.36.8-2, respectively 2.36.9.

**Closed by Nanolx** 2017-08-22 20:42 UTC
